---
title: DemocracyOS France
timezone: UTC
collections:
  brands:
    title: Brands
    output: false
  events:
    title: Events
    output: false
  posts:
    title: Posts
    output: true
  projets:
    title: Projets
    output: false
  members:
    title: members
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    hero: ''
    customclass: ''
    tags: []
    description_hero: ''
    extrait: ''
    auteur: ''
    comments: 'true'
- scope:
    path: ''
    type: members
  values:
    layout: auteur
    avatar: ''
    twitter_username: ''
    description: ''
- scope:
    path: ''
    type: projets
  values:
    visuel: ''
    background_color: ''
    link: ''
    description: ''
- scope:
    path: ''
    type: brands
  values:
    logo: ''
    link: ''
- scope:
    path: ''
    type: events
  values:
    end_date: ''
    type: ''
    visuel: ''
    event_background_color: ''
    full_frame: ''
    description: ''
    texte_bouton: ''
    event_link: ''
email: contact@democracyos.eu
description: Facilitateur de prise de d√©cisions.
baseurl: ''
url: https://arthur-koenig.github.io/dosv3.github.io
twitter_username: DemocracyOS_FR
github_username: democracy-os-fr
github.url: dos.github.io
gems:
- jekyll-paginate
paginate: 6
paginate_path: "/blog/page:num/"
markdown: kramdown
permalink: "/blog/:title"
